### ISSUE TITLE
Could you please share the model weights? The links that you mention both do not have them

### ISSUE THREAD

**Issue by biphasic** [Lornatang/MobileNetV1-PyTorch#4]

**Comment by Lornatang** [comment]
It have.
My Google cloud disk has no storage space. 
See Baidu cloud disk. 
thanks.

**Comment by biphasic** [comment]
Thanks for your quick answer! Unfortunately, the Baidu cloud disk only contains the folder, but no file. On Baidu disk I go to Pytorch -> Classification -> MobileNetV1 and it's empty, whereas the MobileNetV2/V3 folders contain files. However it is V1 that I'm interested in specifically. If you still have the weights available, that would be amazing.  
https://pan.baidu.com/s/1yNs4rqIb004-NKEdKBJtYg?pwd=llot#list/path=%2Fsharelink1017811571-785995367612570%2FPyTorch%2FClassification%2FMobileNetV1&parentPath=%2Fsharelink1017811571-785995367612570

**Comment by Lornatang** [comment]
I upload it in today @biphasic

**Comment by LZelda** [comment]
> Thanks for your quick answer! Unfortunately, the Baidu cloud disk only contains the folder, but no file. On Baidu disk I go to Pytorch -> Classification -> MobileNetV1 and it's empty, whereas the MobileNetV2/V3 folders contain files. However it is V1 that I'm interested in specifically. If you still have the weights available, that would be amazing. https://pan.baidu.com/s/1yNs4rqIb004-NKEdKBJtYg?pwd=llot#list/path=%2Fsharelink1017811571-785995367612570%2FPyTorch%2FClassification%2FMobileNetV1&parentPath=%2Fsharelink1017811571-785995367612570

Excuse me, can you give me a copy of the weight of V1?

**Comment by list0830** [comment]
@biphasic @LZelda Excuse me, have you got the weight of V1?

**Comment by biphasic** [comment]
I don't have it either
